### ISSUE TITLE
Setup code climate.

### ISSUE THREAD

**Issue by yoshinorin** [YoshinoriN/Kinugasa#19]

**Comment by yoshinorin** [comment]
- Auto analyze when someone push to GitHub.
- Deside analiystic pattern.

**Comment by yoshinorin** [comment]
.codeclimate.yml sample.

``` yml
engines:
  fixme:
    enabled: true
    config:
      strings:
      - FIXME
      - BUG
      - CUSTOM
      - HACK
      - TODO
  markdownlint:
    enabled: true
exclude_paths:
- "Test/"
```
